
[package]
name = "LiDARSim"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = {workspace = true}
network-tables = "0.1.3"
rppal = "0.22.1"

[features]
default = ["fyrox/default"]
dylib-engine = ["fyrox/dylib"]
