
[package]
name = "LiDARSim"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = {workspace = true}
network-tables = { version = "0.1.3", features = ["__v4", "client-v4"] }
tokio = "1.44.2"

[features]
default = ["fyrox/default"]
dylib-engine = ["fyrox/dylib"]
